project:
  type: website
  output-dir: docs
  
website:
  favicon: favicon.png
  navbar:
    logo: logo.png
    left:
    - href: About Me.qmd
      text: About Me
    - href: Project.qmd
      text: Project in Y1T1 
    - href: Movie.qmd
      text: Movie 
    - href: index.qmd
      text: Temp
    - about.qmd
    
format:
  html:
    theme: pulse
    css: styles.css
    toc: true
    toc-depth: 3
    toc-location: left